import { chromium } from 'playwright-core'; import { readdirSync, mkdirSync } from 'node:fs';
import { App, StaticTokenAuthenticator, ConfigStore, RoleRegistry, MasterData, createHttpServer } from '../src/index.ts';
function fc(){const r=process.env.PLAYWRIGHT_BROWSERS_PATH??'/opt/pw-browsers';const d=readdirSync(r).find(x=>/^chromium-\d/.test(x))!;return `${r}/${d}/chrome-linux/chrome`;}
mkdirSync('/home/user/Elara/web-shots',{recursive:true});
const PX='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';
const auth=new StaticTokenAuthenticator({o:{actor:'a',tenantId:'jq',role:'owner'}});
const app=new App({authenticator:auth,config:new ConfigStore(),roles:new RoleRegistry(),masterData:new MasterData()});
const B=(m:string,p:string,b?:any)=>app.dispatch({method:m,path:p,bearer:'Bearer o',body:b??{}});
B('PUT','/config',{displayName:'Harbor Homes',country:'US'});
B('POST','/properties',{code:'CURRAL',name:'Praia do Curral'});
B('POST','/properties',{code:'VILA',name:'Vila & Pereque'});
B('POST','/units',{id:'c1',code:'C1',label:'Curral 1',propertyId:'prop-curral'});
B('POST','/units',{id:'c2',code:'C2',label:'Curral 2',propertyId:'prop-curral'});
B('POST','/units',{id:'v1',code:'V1',label:'Vila 1',propertyId:'prop-vila'});
B('PUT','/site-content',{content:{heroTitle:'Harbor — book direct'}});
B('PUT','/site-content',{propertyId:'prop-curral',content:{heroSubtitle:'Beachfront living',units:{c1:{published:true,photoDataUrl:PX}}}});
B('PUT','/site-content',{propertyId:'prop-vila',content:{heroSubtitle:'Village charm'}});
const s=createHttpServer(app); await new Promise<void>(r=>s.listen(0,()=>r())); const port=(s.address() as any).port;
const b=await chromium.launch({executablePath:fc(),args:['--no-sandbox']});
const errs:string[]=[];
const pg=await (await b.newContext({viewport:{width:1180,height:1000}})).newPage();
pg.on('console',m=>{if(m.type()==='error'&&!/ERR_CONNECTION_RESET|ERR_ABORTED|Failed to load resource/.test(m.text()))errs.push(m.text());}); pg.on('pageerror',e=>errs.push('PE:'+e.message));
await pg.goto(`http://127.0.0.1:${port}/site/jq`);
await pg.waitForFunction(()=>document.getElementById('brandName')?.textContent!=='Loading…',{timeout:15000});
await pg.waitForTimeout(400);
const vis=(id:string)=>pg.evaluate((i)=>{const e=document.getElementById(i) as any; return !!e && e.style.display!=='none';},id);
console.log('Communities section visible:', await vis('commSec'));
console.log('community cards (want 2):', await pg.evaluate(()=>document.querySelectorAll('#commBody .card').length));
console.log('flat units hidden on directory:', !(await vis('unitsSec')));
console.log('search bar hidden on directory:', await pg.evaluate(()=>{const s=document.querySelector('.searchbar') as any; return !!s && s.style.display==='none';}));
const hrefs=await pg.evaluate(()=>[...document.querySelectorAll('#commBody a.card')].map(a=>a.getAttribute('href')));
console.log('community links:', JSON.stringify(hrefs));
await pg.screenshot({path:'/home/user/Elara/web-shots/directory.png',fullPage:true});
// click a community → its property page
await pg.evaluate(()=>{ (document.querySelector('#commBody a.card') as any).click(); });
await pg.waitForTimeout(600);
console.log('after click, on a /p/ page:', /\/site\/jq\/p\//.test(pg.url()), '→', pg.url());
console.log(errs.length?('ERRORS:'+errs.join('|')):'NO CONSOLE ERRORS');
await b.close(); s.close();
